#!/bin/sh
# 
# ./script/repl -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.12.0}}}' 
# ./script/repl -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.13.0-master-SNAPSHOT"}} :mvn/repos {"sonatype-oss-public" {:url "https://oss.sonatype.org/content/groups/public/" }}}' 

set -xe

clj "$@" -M:test:nREPL:spec-skip-macros
