#!/bin/bash

set -e

VERSION=$1

if [ -z "$VERSION" ]
  then
    echo "No new version supplied"
    echo "usage: ./script/bump-readme-version <NEW-VERSION>"
    exit 1
fi

./script/bump-readme-version.clj "$VERSION" README.md \
  typed/annotator.jvm/README.md \
  typed/clj.analyzer/README.md \
  typed/clj.checker/README.md \
  typed/clj.runtime/README.md \
  typed/cljc.analyzer/README.md \
  typed/lang.jvm/README.md \
  typed/lib.clojure/README.md \
  typed/lib.core.async/README.md
