name: Test ClojureCLR

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  test-clojureclr:
    runs-on: ubuntu-latest
    # only test main if in typedclojure/typedclojure repo
    if: ${{ !(github.ref == 'refs/heads/main'
              && github.repository != 'typedclojure/typedclojure'
              && github.event_name == 'push')
         }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      
      - name: Install ClojureCLR and cljr
        run: |
          # Install ClojureCLR as a dotnet tool
          dotnet tool install --global Clojure.Main --version 1.12.3-alpha3
          # Install cljr CLI tool
          dotnet tool install --global Clojure.Cljr --version 0.1.0-alpha8
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      
      - name: Verify ClojureCLR and cljr installation
        run: |
          which Clojure.Main || echo "Clojure.Main not in PATH"
          which cljr || echo "cljr not in PATH"
          ls -la ~/.dotnet/tools/
      
      # Commented out temporarily - testing analyzers first
      # - name: Run typed.clj.runtime test suite
      #   run: |
      #     cd $GITHUB_WORKSPACE/typed/clj.runtime
      #     echo "Running typed.clj.runtime test suite with ClojureCLR..."
      #     ./script/test-clr
      
      - name: Run typed.cljc.analyzer test suite
        run: |
          cd $GITHUB_WORKSPACE/typed/cljc.analyzer
          echo "Running typed.cljc.analyzer test suite with ClojureCLR..."
          ./script/test-clr
      
      - name: Run typed.clj.analyzer test suite
        run: |
          cd $GITHUB_WORKSPACE/typed/clj.analyzer
          echo "Running typed.clj.analyzer test suite with ClojureCLR..."
          ./script/test-clr
